-- 1. Create function for automatic updated_at timestamp
CREATE OR REPLACE FUNCTION update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

-- 2. Apply Schema Changes (Generated by Drizzle)
ALTER TABLE "account_metadata" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "account_metadata" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "accounts" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "accounts" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "journal_entries" ADD COLUMN "metadata" jsonb;
ALTER TABLE "journal_entries" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "journal_entries" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "ledgers" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "ledgers" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "profiles" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "profiles" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "transactions" ADD COLUMN "metadata" jsonb;
ALTER TABLE "transactions" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;
ALTER TABLE "transactions" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;

-- 3. Enable Row Level Security (Critical for Supabase)
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ledgers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "journal_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account_metadata" ENABLE ROW LEVEL SECURITY;

-- 4. Create Triggers for automatic updated_at updates
CREATE TRIGGER set_timestamp_profiles BEFORE UPDATE ON "profiles" FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER set_timestamp_ledgers BEFORE UPDATE ON "ledgers" FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER set_timestamp_accounts BEFORE UPDATE ON "accounts" FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER set_timestamp_transactions BEFORE UPDATE ON "transactions" FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER set_timestamp_journal_entries BEFORE UPDATE ON "journal_entries" FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER set_timestamp_account_metadata BEFORE UPDATE ON "account_metadata" FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
